import type { Car, Sales } from "./columnDefs";

export const rowCarData: Car[] = [
  {
    make: "Toyota",
    model: "Celica",
    year: 2000,
    price: 35000,
    releaseDate: new Date(2000, 0, 1),
  },
  {
    make: "Ford",
    model: "Mondeo",
    year: 2001,
    price: 32000,
    releaseDate: new Date(2001, 0, 1),
  },
  {
    make: "Porsche",
    model: "Boxster",
    year: 2002,
    price: 72000,
    releaseDate: new Date(2002, 0, 1),
  },
];

export const rowSalesData: Sales[] = [
  {
    id: 1,
    customer: "Acme",
    region: "Northeast",
    product: "Laptop",
    revenue: 125000,
    status: "won",
  },
  {
    id: 2,
    customer: "Globex",
    region: "South",
    product: "Monitor",
    revenue: 84000,
    status: "won",
  },
  {
    id: 3,
    customer: "Initech",
    region: "West",
    product: "Server",
    revenue: 213000,
    status: "pending",
  },
  {
    id: 4,
    customer: "Umbrella",
    region: "Northeast",
    product: "Laptop",
    revenue: 178000,
    status: "won",
  },
  {
    id: 5,
    customer: "Stark Industries",
    region: "South",
    product: "Server",
    revenue: 315000,
    status: "won",
  },
  {
    id: 6,
    customer: "Wayne Enterprises",
    region: "West",
    product: "Monitor",
    revenue: 156000,
    status: "pending",
  },
  {
    id: 7,
    customer: "Wonka Industries",
    region: "Northeast",
    product: "Monitor",
    revenue: 97000,
    status: "lost",
  },
  {
    id: 8,
    customer: "Cyberdyne Systems",
    region: "South",
    product: "Server",
    revenue: 265000,
    status: "won",
  },
  {
    id: 9,
    customer: "Tyrell Corporation",
    region: "West",
    product: "Laptop",
    revenue: 189000,
    status: "won",
  },
  {
    id: 10,
    customer: "Hooli",
    region: "Northeast",
    product: "Server",
    revenue: 221000,
    status: "pending",
  },
  {
    id: 11,
    customer: "Massive Dynamic",
    region: "South",
    product: "Laptop",
    revenue: 142000,
    status: "won",
  },
  {
    id: 12,
    customer: "Oceanic Airlines",
    region: "West",
    product: "Server",
    revenue: 198000,
    status: "lost",
  },
];
